"""Masaram Gondi glossary web app."""
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
import html, os, tempfile
from gondi_tool import extract_pdf_tables, normalize_rows, read_csv, convert_to_pdf, write_csv
HOST=os.getenv('HOST','0.0.0.0'); PORT=int(os.getenv('PORT','8000'))
FORM='''<!doctype html><html lang="hi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MGST — Masaram Gondi Transcription</title><style>
:root{--ink:#172033;--muted:#64748b;--blue:#3157d5;--violet:#7048c8;--line:#e4e8f0}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;color:var(--ink);background:linear-gradient(135deg,#f5f7ff,#fff 52%,#f7f4ff)}.wrap{max-width:1080px;margin:auto;padding:28px 24px 72px}.nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:70px}.brand{font-size:22px;font-weight:850;letter-spacing:-.04em}.brand span{color:var(--violet)}.github{color:var(--ink);text-decoration:none;border:1px solid var(--line);padding:10px 15px;border-radius:999px;background:#fff;font-size:14px;font-weight:650}.hero{text-align:center;max-width:780px;margin:auto}.eyebrow{display:inline-block;color:var(--violet);background:#eee9ff;padding:8px 14px;border-radius:999px;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:clamp(42px,7vw,78px);line-height:.98;letter-spacing:-.07em;margin:22px 0 20px}.hero h1 em{font-style:normal;background:linear-gradient(100deg,var(--blue),var(--violet));color:transparent;background-clip:text}.hero p{font-size:19px;color:var(--muted);line-height:1.6;margin:0 auto 36px}.card{max-width:760px;margin:48px auto 0;background:#fff;border:1px solid var(--line);border-radius:24px;padding:34px;box-shadow:0 24px 70px #352b7917}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}label{font-size:13px;font-weight:800;display:block;margin-bottom:8px}input,select{width:100%;font:inherit;padding:14px;border:1px solid #ccd4e1;border-radius:11px;background:#fff}input[type=file]{padding:12px}.full{grid-column:1/-1}.button{width:100%;border:0;border-radius:11px;background:linear-gradient(100deg,var(--blue),var(--violet));color:#fff;padding:16px;font:inherit;font-weight:800;font-size:16px;cursor:pointer;margin-top:4px}.hint{font-size:13px;color:var(--muted);margin-top:14px;text-align:center}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;max-width:900px;margin:28px auto}.feature{background:#ffffffaa;border:1px solid var(--line);border-radius:16px;padding:20px}.feature b{display:block;margin-bottom:7px}.feature p{font-size:13px;color:var(--muted);line-height:1.5;margin:0}@media(max-width:650px){.grid,.features{grid-template-columns:1fr}.full{grid-column:auto}.nav{margin-bottom:46px}.card{padding:22px}.hero p{font-size:16px}}
</style><body><div class="wrap"><nav class="nav"><div class="brand">MG<span>ST</span></div><a class="github" href="https://github.com/startpage750/mgst" target="_blank">View on GitHub ↗</a></nav><section class="hero"><div class="eyebrow">Language preservation tool</div><h1>Masaram Gondi<br><em>Transcription</em></h1><p>अपनी glossary PDF या CSV upload करें और पाँच-column Masaram Gondi glossary तैयार करें।</p></section><main class="card"><form action="/convert" method="post" enctype="multipart/form-data"><div class="grid"><div class="full"><label>Glossary PDF or CSV</label><input name="file" type="file" accept=".pdf,.csv,application/pdf,text/csv" required></div><div><label>Output format</label><select name="format"><option value="pdf">PDF glossary</option><option value="csv">CSV spreadsheet</option></select></div><div><label>Expected columns</label><input value="Gondi · Hindi · Hindi अर्थ · English" disabled></div><div class="full"><button class="button">Convert to MGST →</button></div></div><div class="hint">Output: MG Script · Hindi Pronunciation · Roman Gondi · Hindi अर्थ · English Meaning</div></form></main><section class="features"><div class="feature"><b>Unicode accurate</b><p>Masaram Gondi vowels, conjuncts, repha and ra-kara handling.</p></div><div class="feature"><b>Preserves meaning</b><p>Hindi pronunciation, Hindi अर्थ and English meaning stay intact.</p></div><div class="feature"><b>Open source</b><p>Built for community review and language preservation on GitHub.</p></div></section></div></body></html>'''
def reply(h,status,body,typ='text/html; charset=utf-8'):
 d=body if isinstance(body,bytes) else body.encode(); h.send_response(status); h.send_header('Content-Type',typ); h.send_header('Content-Length',str(len(d))); h.end_headers(); h.wfile.write(d)
class Handler(BaseHTTPRequestHandler):
 def do_GET(self): reply(self,200,FORM) if self.path=='/' else reply(self,404,b'Not found','text/plain')
 def do_POST(self):
  if self.path!='/convert': reply(self,404,b'Not found','text/plain'); return
  n=min(int(self.headers.get('Content-Length','0')),30*1024*1024); body=self.rfile.read(n); ct=self.headers.get('Content-Type',''); boundary=('--'+ct.split('boundary=',1)[1].strip('"')).encode(); fields={}
  for p in body.split(boundary)[1:-1]:
   if b'\r\n\r\n' not in p: continue
   hs,v=p.strip(b'\r\n-').split(b'\r\n\r\n',1); s=hs.decode('latin1','ignore'); name='name="'
   if name in s: fields[s.split(name,1)[1].split('"',1)[0]]=v
  data=fields.get('file',b''); fmt=fields.get('format',b'pdf').decode(); suffix='.csv' if data[:4]!=b'%PDF' else '.pdf'
  if not data: reply(self,400,b'No file','text/plain'); return
  try:
   with tempfile.TemporaryDirectory() as d:
    source=Path(d)/('input'+suffix); out=Path(d)/('output.'+fmt); source.write_bytes(data); rows=read_csv(source) if suffix=='.csv' else extract_pdf_tables(source); normalized=normalize_rows(rows); convert_to_pdf(normalized,out,os.getenv('GONDI_FONT_PATH')) if fmt=='pdf' else write_csv(normalized,out); result=out.read_bytes()
   reply(self,200,result,'application/pdf' if fmt=='pdf' else 'text/csv; charset=utf-8')
  except Exception as e: reply(self,422,html.escape(str(e)),'text/plain; charset=utf-8')
if __name__=='__main__': print(f'Listening on http://{HOST}:{PORT}'); ThreadingHTTPServer((HOST,PORT),Handler).serve_forever()
